# Site settings
# --------------
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl = "/su-hugo-public" # The subpath of your site, e.g. / or /blog